### ISSUE TITLE
I do not see label event in list 

### ISSUE THREAD

**Issue by JiDai** [keithclark/gadebugger#24]
The event label is not shown on list, I have  just "Category / Action". Is it a feature or bug ? 
:)

**Comment by keithclark** [comment]
The event label (and value) don't show in the beacon list but they are visible in the beacon inspector under the "Event Data" heading. Originally this was by design but I've already [added the label and value](https://github.com/keithclark/gadebugger/blob/12c247cddaa69def32f3a52001d55fecdd771e90/src/core/api.js#L51-L56) ready for the next release.

**Comment by JiDai** [comment]
Ok, thanks!
